// -----------------------------------------
// Generated by Vitte compiler (C++ backend)
// -----------------------------------------

#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

